[package]
name = "varsig"
version = "0.1.2"
edition = "2021"
authors = ["Dave Huseby <dwh@linuxprogrammer.org>"]
description = "Varsig self-describing signature implementation"
repository = "https://github.com/cryptidtech/varsig.git"
readme = "README.md"
license = "Apache-2.0"

[dependencies]
anyhow = "1.0"
hex = "0.4"
multibase = "0.9"
multicodec = { version = "0.2", git = "https://github.com/cryptidtech/rust-multicodec.git" }
serde = "1.0"
serde_derive = "1.0"
structopt = "0.3"
thiserror = "1.0"
unsigned-varint = "0.7"
